version: '3'

services:
  cart:
    container_name: cart
    build: ./cart
    ports:
      - "8081:8080"
    environment:
      - CONFIG_PATH=/config.yaml
    depends_on:
      loms:
        condition: service_started

  loms:
    container_name: loms
    build: ./loms
    ports:
      - "8082:8080"
      - "50051:50050"
    environment:
      - CONFIG_PATH=/config.yaml
